name: vercel_dart
description: A utility library for writing serverless functions in the Vercel Dart Runtime.
version: 1.0.0
repository: https://github.com/frencojobs/vercel-dart

publish_to: none # until the PR #24 is merged

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aws_lambda_dart_runtime: ^1.1.0
  # aws_lambda_dart_runtime:
  #  git: https://github.com/soahyle/aws-lambda-dart-runtime
  json_annotation: ^4.1.0
  shelf: ^1.2.0

dev_dependencies:
  build_runner: ^2.0.6
  import_sorter: ^4.6.0
  json_serializable: ^5.0.0
  lint: ^1.5.3
  test: ^1.17.10

scripts:
  format: dartfmt -w .
  sort:
    imports: pub run import_sorter:main *

import_sorter:
  comments: false
